### ISSUE TITLE
[Possible BUG?] Filename Length with invalid characters for O/S

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [Serene-Arc/bulk-downloader-for-reddit#925]
- [ X ] I am reporting a _possible_ bug.
- [ X ] I am running the latest version of BDfR (Every version ive used is affected)
- [ X ] I have read the [Opening an issue](https://github.com/aliparlakci/bulk-downloader-for-reddit/blob/master/docs/CONTRIBUTING.md#opening-an-issue)

## Description
Filenames are excessively long and Samba/Windows cannot properly process them.
Is there a way to set a limit to filename length in BDFR?
Also can it be set up to remove special characters like 🤤 👌 ☁?

## Command
N/A

## Environment (please complete the following information)
- OS: FreeBSD 13
- Python version 3.9

## Logs
Shouldnt require one

**Comment by Serene-Arc** [comment]
This is a known bug. You're basically tricking the BDFR with regards to what considerations it should use. Linux (and Unix in general) is much more permissive than Windows. Where possible, we use Linux restraints since it's just more complete. But you're running it on UNIX while having Windows constraints.

#746 fixes this issue. You need to pull from development and use `--filename-restriction-scheme windows` to force the BDFR to use the Windows limits.

**Comment by MachiavelliSeraphim** [comment]
Thank You :)
That covers just about every quirk or problem ive had over the years!
